#!/bin/bash
# ANSWER KEY - Use this to verify your manual attempts

cd ~/cyber_investigation/logs

echo "CHALLENGE ANSWERS WITH FULL COMMANDS:"
echo "======================================"
echo ""
echo "Challenge 1: Count lines with IP 192.168.1.105"
echo "Command: grep -F '192.168.1.105' access.log | wc -l"
echo "Answer: $(grep -F '192.168.1.105' access.log | wc -l)"
echo ""
echo "Challenge 2: Count failed SSH attempts"
echo "Command: grep 'Failed password' auth.log | wc -l"
echo "Answer: $(grep 'Failed password' auth.log | wc -l)"
echo ""
echo "Challenge 3: Count unique IPs in access.log"
echo "Command: grep -oP '\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}' access.log | sort -u | wc -l"
echo "Answer: $(grep -oP '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' access.log | sort -u | wc -l)"
echo ""
echo "Challenge 4: Count ERROR or FATAL messages"
echo "Command: grep -P 'ERROR|FATAL' application.log | wc -l"
echo "Answer: $(grep -P 'ERROR|FATAL' application.log | wc -l)"
echo ""
echo "Challenge 5: Most active IP address"
echo "Command: grep -oP '\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}' access.log | sort | uniq -c | sort -rn | head -1"
echo "Answer: $(grep -oP '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' access.log | sort | uniq -c | sort -rn | head -1 | awk '{print $2}')"
echo ""
echo "Challenge 6: Count suspicious user agents"
echo "Command: grep -P 'curl|wget|python|scanner' access.log | wc -l"
echo "Answer: $(grep -P 'curl|wget|python|scanner' access.log | wc -l)"
echo ""
echo "Challenge 7: SQL injection attempts"
echo "Command: grep -P \"(--|'|union|select)\" access.log | wc -l"
echo "Answer: $(grep -P "(--|'|union|select)" access.log | wc -l)"
echo ""
echo "Challenge 8: Base64 strings in suspicious.txt"
echo "Command: grep -P '[A-Za-z0-9+/]{20,}={0,2}' suspicious.txt | wc -l"
echo "Answer: $(grep -P '[A-Za-z0-9+/]{20,}={0,2}' suspicious.txt | wc -l)"
echo ""
echo "Challenge 9: Most frequent successful login user"
echo "Command: grep 'Accepted' auth.log | grep -oP 'for \\K\\w+' | sort | uniq -c | sort -rn | head -1"
echo "Answer: $(grep 'Accepted' auth.log | grep -oP 'for \K\w+' | sort | uniq -c | sort -rn | head -1 | awk '{print $2}')"
echo ""
echo "Challenge 10: Count IPs using POST/PUT/DELETE"
echo "Command: grep -P '(POST|PUT|DELETE)' access.log | grep -oP '\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}' | sort -u | wc -l"
echo "Answer: $(grep -P '(POST|PUT|DELETE)' access.log | grep -oP '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' | sort -u | wc -l)"
