#!/bin/bash
# SOLUTIONS - Complete answer key with commands and expected output
# Location: ~/cyber_investigation/challenges/solutions.sh

cd ~/cyber_investigation/logs

echo "CHALLENGE ANSWERS WITH FULL COMMANDS:"
echo "======================================"
echo ""
echo "Challenge 1: Count lines with IP 192.168.1.105"
echo "Command: grep -F '192.168.1.105' access.log | wc -l"
echo "Answer: $(grep -F '192.168.1.105' access.log | wc -l)"
echo ""
echo "Challenge 2: Count failed SSH attempts"
echo "Command: grep 'Failed password' auth.log | wc -l"
echo "Answer: $(grep 'Failed password' auth.log | wc -l)"
echo ""
echo "Challenge 3: Count unique IPs in access.log"
echo "Command: grep -oP '\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}' access.log | sort -u | wc -l"
echo "Answer: $(grep -oP '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' access.log | sort -u | wc -l)"
echo ""
echo "Challenge 4: Count ERROR or FATAL messages"
echo "Command: grep -P 'ERROR|FATAL' application.log | wc -l"
echo "Answer: $(grep -P 'ERROR|FATAL' application.log | wc -l)"
echo ""
echo "Challenge 5: Most active IP address"
echo "Command: grep -oP '\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}' access.log | sort | uniq -c | sort -rn | head -1"
echo "Answer: $(grep -oP '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' access.log | sort | uniq -c | sort -rn | head -1 | awk '{print $2}')"
echo ""
echo "Challenge 6: Count suspicious user agents"
echo "Command: grep -P 'curl|wget|python|scanner' access.log | wc -l"
echo "Answer: $(grep -P 'curl|wget|python|scanner' access.log | wc -l)"
echo ""
echo "Challenge 7: SQL injection attempts"
echo "Command: grep -P \"(--|'|union|select)\" access.log | wc -l"
echo "Answer: $(grep -P "(--|'|union|select)" access.log | wc -l)"
echo ""
echo "Challenge 8: Base64 strings in suspicious.txt"
echo "Command: grep -P '[A-Za-z0-9+/]{20,}={0,2}' suspicious.txt | wc -l"
echo "Answer: $(grep -P '[A-Za-z0-9+/]{20,}={0,2}' suspicious.txt | wc -l)"
echo ""
echo "Challenge 9: Most frequent successful login user"
echo "Command: grep 'Accepted' auth.log | grep -oP 'for \\K\\w+' | sort | uniq -c | sort -rn | head -1"
echo "Answer: $(grep 'Accepted' auth.log | grep -oP 'for \K\w+' | sort | uniq -c | sort -rn | head -1 | awk '{print $2}')"
echo ""
echo "Challenge 10: Count IPs using POST/PUT/DELETE"
echo "Command: grep -P '(POST|PUT|DELETE)' access.log | grep -oP '\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}' | sort -u | wc -l"
echo "Answer: $(grep -P '(POST|PUT|DELETE)' access.log | grep -oP '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' | sort -u | wc -l)"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "LEVEL 5: ADVANCED REGEX MASTERY"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Challenge 11: Count unique email domains in suspicious.txt"
echo "Command: grep -oP '[a-zA-Z0-9._%+-]+@\\K[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}' suspicious.txt | sort -u | wc -l"
echo "Answer: $(grep -oP '[a-zA-Z0-9._%+-]+@\K[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}' suspicious.txt | sort -u | wc -l)"
echo ""
echo "Challenge 12: Count lines with phone numbers in suspicious.txt"
echo "Command: grep -P '(\\+\\d{1,2}[- ])?\\(?(\\d{3})\\)?[- .]?(\\d{3})[- .]?(\\d{4})' suspicious.txt | wc -l"
echo "Answer: $(grep -P '(\+\d{1,2}[- ])?\(?(\d{3})\)?[- .]?(\d{3})[- .]?(\d{4})' suspicious.txt | wc -l)"
echo ""
echo "Challenge 13: Count lines with IPv6 addresses in suspicious.txt"
echo "Command: grep -P '([0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}' suspicious.txt | wc -l"
echo "Answer: $(grep -P '([0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}' suspicious.txt | wc -l)"
echo ""
echo "Challenge 14: Count lines with JWT tokens in suspicious.txt"
echo "Command: grep -P 'eyJ[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+' suspicious.txt | wc -l"
echo "Answer: $(grep -P 'eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+' suspicious.txt | wc -l)"
echo ""
echo "Challenge 15: Count lines with MD5 or SHA256 hashes in suspicious.txt"
echo "Command: grep -P '\\b[a-f0-9]{32}\\b|\\b[a-f0-9]{64}\\b' suspicious.txt | wc -l"
echo "Answer: $(grep -P '\b[a-f0-9]{32}\b|\b[a-f0-9]{64}\b' suspicious.txt | wc -l)"
echo ""
echo "Challenge 16: Count unique service names in parentheses at end of lines in network.log"
echo "Command: grep -oP '\\(\\K[A-Z][a-z]+(?=\\)\$)' network.log | sort -u | wc -l"
echo "Answer: $(grep -oP '\(\K[A-Z][a-z]+(?=\)$)' network.log | sort -u | wc -l)"
echo ""
echo "Challenge 17: Count TLS 1.2 or 1.3 connections in network.log"
echo "Command: grep -P 'TLS1\\.(2|3)' network.log | wc -l"
echo "Answer: $(grep -P 'TLS1\.(2|3)' network.log | wc -l)"
echo ""
echo "Challenge 18: Count log entries between 10:50 and 11:10 in application.log"
echo "Command: grep -P '(10:5[0-9]|11:0[0-9]|11:10):' application.log | wc -l"
echo "Answer: $(grep -P '(10:5[0-9]|11:0[0-9]|11:10):' application.log | wc -l)"
echo ""
echo "Challenge 19: Count unique MAC addresses in suspicious.txt"
echo "Command: grep -oP '([0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2}' suspicious.txt | sort -u | wc -l"
echo "Answer: $(grep -oP '([0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2}' suspicious.txt | sort -u | wc -l)"
echo ""
echo "Challenge 20: Find most common HTTP status code in access.log"
echo "Command: grep -oP 'HTTP/\\d\\.\\d\" \\K\\d{3}' access.log | sort | uniq -c | sort -rn | head -1"
echo "Answer: $(grep -oP 'HTTP/\d\.\d" \K\d{3}' access.log | sort | uniq -c | sort -rn | head -1 | awk '{print $2}')"
